version: "3.8"

services:
    # FRONTEND (VITE)
    frontend:
        build: ./client
        ports:
            - "5173:5173"
        depends_on:
            - backend
        stdin_open: true
        tty: true
        networks:
            - mern-app
        container_name: frontend

    # BACKEND (NODE)
    backend:
        build: ./
        ports:
            - "5000:5000"
        networks:
            - mern-app
        container_name: backend
        env_file:
            - ./.env

networks:
    mern-app:
        driver: bridge
